
INSERT INTO "SYSTEM"."BOOKS" (ISBN, TITLE, AUTHOR, PUBLISHER, YEAR_PUBLISHED, GENRE, COPIES_AVAILABLE) VALUES ('1', 'To Kill a Mockingbird', 'Harper Lee', 'haper lee', '2001', 'Horror', '15000')
INSERT INTO "SYSTEM"."BOOKS" (ISBN, TITLE, AUTHOR, PUBLISHER, YEAR_PUBLISHED, GENRE, COPIES_AVAILABLE) VALUES ('2', 'MY story', 'Daniels', 'Daniels', '2003', 'Education', '17000')
INSERT INTO "SYSTEM"."BOOKS" (ISBN, TITLE, AUTHOR, PUBLISHER, YEAR_PUBLISHED, GENRE, COPIES_AVAILABLE) VALUES ('3', 'Love story', 'ketty', 'Shalob]n', '2004', 'Roman', '20000')

Commit Successful

